MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :bands
  resource :session, only: [:new, :create, :destroy]
end

MusicApp/app/models/album.rb
class Album < ApplicationRecord
  validates :title, presence: true, uniqueness: true 
  validates :yr, presence: true 

  belongs_to :band,
  foreign_key: :band_id,
  class_name: 'Band'
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  foreign_key: :band_id,
  class_name: 'Album'
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  before_validation :ensure_session_token


  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil 
  end 

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end 

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end 

  def reset_session_token!
    self.session_token ||= SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end   

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end 

  def is_password?(password)
    bcrypt_password = BCrypt::Password.new(self.password_digest)
    bcrypt_password.is_password?(password)
  end
  
  
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def login!(user)
    session[:session_token] = user.reset_session_token! if user 
  end 

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end 

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end 

  def logged_in?
    !!current_user
  end 
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index 
    @bands = Band.all
    render :index 
  end 

  def new
    render :new
  end 

  def create
    @band = Band.new(band_params)
    if @band.save!
      redirect_to band_url(@band)
    else 
      redirect_to new_band_url
    end 
  end 

  def edit

  end 

  def update 

  end 

  def destroy

  end 

  def show
    @band = Band.find(params[:id])
    render :show
  end 

  private 

  def band_params
    params.require(:band).permit(:name)
  end 
end 

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new 
    render :new
  end 

  def create 
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user 
      login!(user)
      redirect_to user_url(user)
    else 
      redirect_to new_session_url
    end 
  end 

  def destroy
    logout!
    redirect_to users_url
  end 
end 

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all
    render :index 
  end 

  def new 
    @user = User.new
    render :new
  end 

  def create 
    user = User.new(user_params)
    if user.save!
      login!(@user)
      redirect_to user_url(user)
    else 
      redirect_to new_user_url
    end 
  end 

  def show
    @user = User.find(params[:id])
    render :show
  end 

  private 

  def user_params
    params.require(:user).permit(:email, :password)
  end 
end 

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/session_helper.rb
module SessionHelper
end

MusicApp/app/views/bands/_band_form.html.erb
<form action="<%= action%>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="name">Band Name:
  <input type="text" name="band[name]" value="">
  </label>

  <input type="submit" value="<%= button%>">

</form>

MusicApp/app/views/bands/index.html.erb
<h2>The Tour Bus Includes:</h2>

<ul>
<% @bands.each do |band| %>
  <li><a href="<%= band_url(band)%>"><%= band.name %></a></li>
<% end  %>
</ul>

MusicApp/app/views/bands/new.html.erb
<h2>Enter the Name of a Band to include!</h2>

<%= render 'band_form', action: bands_url, button: "Add band!" %>

MusicApp/app/views/bands/show.html.erb
<h2>Check out this Band!!</h2>

<h3> <%= @band.name %> </h3>

<a href=" <%= bands_url%>">All Bands</a>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header>
<h1>Music App</h1>
<div>
  <a href="<%= new_session_url%>">Log In?</a>

  <a href="<%= new_user_url%>">Sign Up!</a>

  <% if logged_in? %>
    <a href="<%= user_url(current_user)%>"><%= current_user.email%></a>
  <% end  %>
</div>

</header>
  <body>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/_forms.html.erb
<form action="<%= action %>" method="post">
<input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">


<label for="email"> Email:
  <input type="text" name="user[email]" value="">
</label>

<label for="password"> Password:
  <input type="password" name="user[password]" value="">
</label>


  <input type="submit" value="<%=button%>">
</form>

MusicApp/app/views/users/index.html.erb
<h2>Hello Friend!</h2>

MusicApp/app/views/users/new.html.erb
<h2>Create a New User!</h2>

<%= render 'forms', action: users_url, button: "Create!" %>

MusicApp/app/views/users/show.html.erb
<h2>Welcome <%= @user.email%>!</h2>

<% if logged_in? %>
  <form action="<%= session_url%>" method="post">
  <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Logout?">
  </form>

<% else %>
  <form action="<%= new_session_url%>" method="post">
  <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="get">
    <input type="submit" value="Log In?">
  </form>
<% end  %>